Exception in thread "main" org.jboss.netty.channel.ChannelException: Failed to bind to: /0.0.0.0:43594
	at org.jboss.netty.bootstrap.ServerBootstrap.bind(ServerBootstrap.java:306)
	at Auora.network.ChannelBinder.bind(ChannelBinder.java:51)
	at Auora.GameServer.<init>(GameServer.java:122)
	at Auora.GameServer.main(GameServer.java:149)
Caused by: java.net.BindException: Address already in use: bind
	at sun.nio.ch.Net.bind0(Native Method)
	at sun.nio.ch.Net.bind(Unknown Source)
	at sun.nio.ch.Net.bind(Unknown Source)
	at sun.nio.ch.ServerSocketChannelImpl.bind(Unknown Source)
	at sun.nio.ch.ServerSocketAdaptor.bind(Unknown Source)
	at org.jboss.netty.channel.socket.nio.NioServerSocketPipelineSink.bind(NioServerSocketPipelineSink.java:148)
	at org.jboss.netty.channel.socket.nio.NioServerSocketPipelineSink.handleServerSocket(NioServerSocketPipelineSink.java:100)
	at org.jboss.netty.channel.socket.nio.NioServerSocketPipelineSink.eventSunk(NioServerSocketPipelineSink.java:74)
	at org.jboss.netty.channel.Channels.bind(Channels.java:468)
	at org.jboss.netty.channel.AbstractChannel.bind(AbstractChannel.java:170)
	at org.jboss.netty.bootstrap.ServerBootstrap$Binder.channelOpen(ServerBootstrap.java:351)
	at org.jboss.netty.channel.Channels.fireChannelOpen(Channels.java:176)
	at org.jboss.netty.channel.socket.nio.NioServerSocketChannel.<init>(NioServerSocketChannel.java:85)
	at org.jboss.netty.channel.socket.nio.NioServerSocketChannelFactory.newChannel(NioServerSocketChannelFactory.java:142)
	at org.jboss.netty.channel.socket.nio.NioServerSocketChannelFactory.newChannel(NioServerSocketChannelFactory.java:90)
	at org.jboss.netty.bootstrap.ServerBootstrap.bind(ServerBootstrap.java:285)
	... 3 more
java.lang.NullPointerException
	at Auora.model.player.Player.tick(Player.java:636)
	at Auora.service.logic.task.PreTickTask.run(PreTickTask.java:34)
	at Auora.service.logic.TaskExecutor.executeTasks(TaskExecutor.java:25)
	at Auora.service.logic.LogicService.run(LogicService.java:136)
	at java.lang.Thread.run(Unknown Source)
